export type AdStatus = "Pending" | "Active" | "Rejected" | "Sold"

export type Ad = {
  id: string
  title: string
  category: string
  location: string
  user: { name: string; initials: string }
  status: AdStatus
  price: number
  postedDate: string
  expiryDate: string
  featured: boolean
  views: number
  clicks: number
  favorites: number
  rejectionReason?: string
  description: string
}

export const categories = [
  "Motors",
  "Real Estate",
  "Mobile & Tablets",
  "Electronics & Leisure",
  "Services",
  "Jobs",
] as const

export const statuses: AdStatus[] = ["Pending", "Active", "Rejected", "Sold"]

function initialsOf(name: string) {
  return name
    .split(" ")
    .map((p) => p[0])
    .slice(0, 2)
    .join("")
    .toUpperCase()
}

function ad(input: Omit<Ad, "user" | "views" | "clicks" | "favorites"> & {
  userName: string
  views: number
  clicks: number
}): Ad {
  return {
    ...input,
    user: { name: input.userName, initials: initialsOf(input.userName) },
    favorites: Math.round(input.views * 0.04),
  }
}

export const adsData: Ad[] = [
  ad({
    id: "AD-10231",
    title: "Toyota Land Cruiser GXR 2022 — GCC Specs",
    category: "Motors",
    location: "Muscat, Al Khuwair",
    userName: "Sara Al Balushi",
    status: "Active",
    price: 18500,
    postedDate: "2026-07-28",
    expiryDate: "2026-09-11",
    featured: true,
    views: 4820,
    clicks: 612,
    description:
      "Immaculate condition, full service history, single owner, GCC specs with regional warranty remaining.",
  }),
  ad({
    id: "AD-10232",
    title: "3BHK Villa for Rent — Al Mouj Waterfront",
    category: "Real Estate",
    location: "Muscat, Al Mouj",
    userName: "Ahmed Al Farsi",
    status: "Pending",
    price: 950,
    postedDate: "2026-08-10",
    expiryDate: "2026-09-24",
    featured: false,
    views: 210,
    clicks: 34,
    description:
      "Sea-view villa, private garden, shared pool access, unfurnished, available from September.",
  }),
  ad({
    id: "AD-10233",
    title: "iPhone 15 Pro Max 256GB — Natural Titanium",
    category: "Mobile & Tablets",
    location: "Muscat, Ruwi",
    userName: "Fatma Al Hinai",
    status: "Rejected",
    price: 265,
    postedDate: "2026-08-09",
    expiryDate: "2026-09-23",
    featured: false,
    views: 98,
    clicks: 11,
    rejectionReason:
      "Listed price appears to be a down-payment amount, not the full price. Please update to the realistic full price before resubmitting.",
    description: "Barely used, with box and accessories, battery health 97%.",
  }),
  ad({
    id: "AD-10234",
    title: "Nissan Patrol Super Safari 2020",
    category: "Motors",
    location: "Sohar",
    userName: "Khalid Al Riyami",
    status: "Sold",
    price: 22900,
    postedDate: "2026-06-14",
    expiryDate: "2026-07-29",
    featured: false,
    views: 6210,
    clicks: 845,
    description: "V8 engine, well maintained, tinted windows, new tires.",
  }),
  ad({
    id: "AD-10235",
    title: "MacBook Pro 14\" M3 Pro — 18GB/512GB",
    category: "Electronics & Leisure",
    location: "Muscat, Qurm",
    userName: "Yousuf Al Abri",
    status: "Active",
    price: 620,
    postedDate: "2026-08-05",
    expiryDate: "2026-09-19",
    featured: true,
    views: 1540,
    clicks: 203,
    description: "Space Black, AppleCare+ until 2027, original packaging included.",
  }),
  ad({
    id: "AD-10236",
    title: "Home Cleaning & Deep Sanitization Service",
    category: "Services",
    location: "Muscat, Al Khoud",
    userName: "Maryam Al Zadjali",
    status: "Active",
    price: 15,
    postedDate: "2026-08-07",
    expiryDate: "2026-09-21",
    featured: false,
    views: 430,
    clicks: 58,
    description: "Weekly and one-time packages, eco-friendly products, trained staff.",
  }),
  ad({
    id: "AD-10237",
    title: "Senior Accountant — Full Time, Muscat",
    category: "Jobs",
    location: "Muscat, Ghala",
    userName: "Al Falaj Trading LLC",
    status: "Pending",
    price: 0,
    postedDate: "2026-08-11",
    expiryDate: "2026-09-25",
    featured: false,
    views: 76,
    clicks: 9,
    description: "5+ years GCC experience, CMA preferred, immediate joiners preferred.",
  }),
  ad({
    id: "AD-10238",
    title: "Land Rover Range Rover Sport 2021 HSE",
    category: "Motors",
    location: "Muscat, Bosher",
    userName: "Salim Al Kindi",
    status: "Active",
    price: 26900,
    postedDate: "2026-08-01",
    expiryDate: "2026-09-15",
    featured: true,
    views: 3980,
    clicks: 511,
    description: "Full agency service history, panoramic roof, 22-inch rims.",
  }),
  ad({
    id: "AD-10239",
    title: "2BHK Apartment for Sale — Muscat Hills",
    category: "Real Estate",
    location: "Muscat, Muscat Hills",
    userName: "Huda Al Saidi",
    status: "Active",
    price: 78000,
    postedDate: "2026-07-20",
    expiryDate: "2026-09-03",
    featured: false,
    views: 1210,
    clicks: 145,
    description: "Golf course view, fitted kitchen, covered parking, freehold title.",
  }),
  ad({
    id: "AD-10240",
    title: "Samsung Galaxy S24 Ultra 512GB",
    category: "Mobile & Tablets",
    location: "Sur",
    userName: "Badar Al Mamari",
    status: "Active",
    price: 310,
    postedDate: "2026-08-06",
    expiryDate: "2026-09-20",
    featured: false,
    views: 640,
    clicks: 71,
    description: "Titanium Gray, brand new sealed box, warranty until 2027.",
  }),
  ad({
    id: "AD-10241",
    title: "Sony PlayStation 5 Slim + 3 Games",
    category: "Electronics & Leisure",
    location: "Muscat, Seeb",
    userName: "Rashid Al Hosni",
    status: "Rejected",
    price: 180,
    postedDate: "2026-08-08",
    expiryDate: "2026-09-22",
    featured: false,
    views: 54,
    clicks: 6,
    rejectionReason:
      "Product photos do not match the description. Please upload clear images of the actual item.",
    description: "Lightly used, includes extra controller and carry case.",
  }),
  ad({
    id: "AD-10242",
    title: "AC Maintenance & Repair — Same Day Service",
    category: "Services",
    location: "Muscat, Al Amerat",
    userName: "Gulf Comfort Services",
    status: "Active",
    price: 12,
    postedDate: "2026-07-30",
    expiryDate: "2026-09-13",
    featured: true,
    views: 890,
    clicks: 122,
    description: "Split & central AC servicing, gas top-up, free inspection.",
  }),
  ad({
    id: "AD-10243",
    title: "Site Engineer — Contract, Duqm",
    category: "Jobs",
    location: "Al Wusta, Duqm",
    userName: "Horizon Contracting",
    status: "Active",
    price: 0,
    postedDate: "2026-08-02",
    expiryDate: "2026-09-16",
    featured: false,
    views: 302,
    clicks: 41,
    description: "Civil engineering background, 3+ years, valid Oman driving license required.",
  }),
  ad({
    id: "AD-10244",
    title: "BMW X5 xDrive40i 2023",
    category: "Motors",
    location: "Muscat, Al Khuwair",
    userName: "Noora Al Lawati",
    status: "Pending",
    price: 32500,
    postedDate: "2026-08-11",
    expiryDate: "2026-09-25",
    featured: false,
    views: 145,
    clicks: 19,
    description: "M Sport package, low mileage, under agency warranty until 2026.",
  }),
  ad({
    id: "AD-10245",
    title: "Studio Apartment for Rent — Ruwi",
    category: "Real Estate",
    location: "Muscat, Ruwi",
    userName: "Ali Al Balushi",
    status: "Sold",
    price: 220,
    postedDate: "2026-06-25",
    expiryDate: "2026-08-09",
    featured: false,
    views: 780,
    clicks: 96,
    description: "Furnished, close to souq, includes utilities.",
  }),
  ad({
    id: "AD-10246",
    title: "iPad Air 5th Gen 64GB WiFi",
    category: "Mobile & Tablets",
    location: "Nizwa",
    userName: "Zainab Al Hajri",
    status: "Active",
    price: 145,
    postedDate: "2026-08-04",
    expiryDate: "2026-09-18",
    featured: false,
    views: 320,
    clicks: 38,
    description: "Space Gray, minor scuff on back, works perfectly.",
  }),
  ad({
    id: "AD-10247",
    title: "DJI Mini 4 Pro Drone — Fly More Combo",
    category: "Electronics & Leisure",
    location: "Muscat, Azaiba",
    userName: "Hamed Al Balushi",
    status: "Active",
    price: 395,
    postedDate: "2026-07-26",
    expiryDate: "2026-09-09",
    featured: true,
    views: 1120,
    clicks: 168,
    description: "Used twice, all original accessories, extra battery included.",
  }),
  ad({
    id: "AD-10248",
    title: "Wedding & Event Photography Package",
    category: "Services",
    location: "Muscat, Qurm",
    userName: "Layla Studios",
    status: "Active",
    price: 250,
    postedDate: "2026-07-22",
    expiryDate: "2026-09-05",
    featured: false,
    views: 610,
    clicks: 83,
    description: "Full-day coverage, drone shots, same-week edited highlight reel.",
  }),
  ad({
    id: "AD-10249",
    title: "Digital Marketing Executive — Full Time",
    category: "Jobs",
    location: "Muscat, Qurm",
    userName: "Zoqo Media Group",
    status: "Rejected",
    price: 0,
    postedDate: "2026-08-09",
    expiryDate: "2026-09-23",
    featured: false,
    views: 42,
    clicks: 5,
    rejectionReason: "Job description duplicated from another active listing. Please provide original content.",
    description: "2+ years experience with paid social and SEO, portfolio required.",
  }),
  ad({
    id: "AD-10250",
    title: "Ford F-150 Raptor 2021",
    category: "Motors",
    location: "Muscat, Al Ghubra",
    userName: "Turki Al Balushi",
    status: "Active",
    price: 24900,
    postedDate: "2026-07-31",
    expiryDate: "2026-09-14",
    featured: false,
    views: 2340,
    clicks: 289,
    description: "Loaded with options, carbon fiber trim, upgraded exhaust.",
  }),
  ad({
    id: "AD-10251",
    title: "Commercial Shop for Rent — Muttrah Souq",
    category: "Real Estate",
    location: "Muscat, Muttrah",
    userName: "Al Rawahi Properties",
    status: "Active",
    price: 480,
    postedDate: "2026-07-18",
    expiryDate: "2026-09-01",
    featured: true,
    views: 940,
    clicks: 112,
    description: "High foot traffic location, ground floor, 45 sqm.",
  }),
  ad({
    id: "AD-10252",
    title: "Xiaomi 14 Ultra 512GB",
    category: "Mobile & Tablets",
    location: "Salalah",
    userName: "Mohammed Al Kathiri",
    status: "Pending",
    price: 285,
    postedDate: "2026-08-11",
    expiryDate: "2026-09-25",
    featured: false,
    views: 63,
    clicks: 7,
    description: "New, sealed, GCC warranty, Leica optics.",
  }),
  ad({
    id: "AD-10253",
    title: "Canon EOS R6 Mark II + 24-105mm Lens",
    category: "Electronics & Leisure",
    location: "Muscat, Al Khuwair",
    userName: "Aisha Al Hooti",
    status: "Active",
    price: 1450,
    postedDate: "2026-07-27",
    expiryDate: "2026-09-10",
    featured: true,
    views: 870,
    clicks: 134,
    description: "Low shutter count, includes extra battery and 64GB CFexpress card.",
  }),
  ad({
    id: "AD-10254",
    title: "Personal Trainer — In-home Sessions",
    category: "Services",
    location: "Muscat, Madinat Sultan Qaboos",
    userName: "Peak Fitness Oman",
    status: "Active",
    price: 20,
    postedDate: "2026-08-03",
    expiryDate: "2026-09-17",
    featured: false,
    views: 380,
    clicks: 52,
    description: "Certified trainers, custom programs, nutrition guidance included.",
  }),
  ad({
    id: "AD-10255",
    title: "Warehouse Supervisor — Full Time, Sohar",
    category: "Jobs",
    location: "Sohar Freezone",
    userName: "Batinah Logistics",
    status: "Active",
    price: 0,
    postedDate: "2026-07-29",
    expiryDate: "2026-09-12",
    featured: false,
    views: 210,
    clicks: 27,
    description: "Inventory management experience, forklift license a plus.",
  }),
  ad({
    id: "AD-10256",
    title: "Mercedes-Benz GLE 450 2022",
    category: "Motors",
    location: "Muscat, Madinat Sultan Qaboos",
    userName: "Reem Al Wahaibi",
    status: "Sold",
    price: 34900,
    postedDate: "2026-06-10",
    expiryDate: "2026-07-25",
    featured: false,
    views: 5120,
    clicks: 690,
    description: "AMG line, panoramic sunroof, single owner, agency maintained.",
  }),
  ad({
    id: "AD-10257",
    title: "Furnished 1BHK for Rent — Al Khuwair",
    category: "Real Estate",
    location: "Muscat, Al Khuwair",
    userName: "Saif Al Nabhani",
    status: "Pending",
    price: 320,
    postedDate: "2026-08-10",
    expiryDate: "2026-09-24",
    featured: false,
    views: 88,
    clicks: 12,
    description: "Fully furnished, gym & pool access, near shopping mall.",
  }),
  ad({
    id: "AD-10258",
    title: "Sony WH-1000XM5 Headphones",
    category: "Electronics & Leisure",
    location: "Muscat, Al Ghubra",
    userName: "Talal Al Rashdi",
    status: "Active",
    price: 78,
    postedDate: "2026-08-06",
    expiryDate: "2026-09-20",
    featured: false,
    views: 410,
    clicks: 49,
    description: "Barely used, comes with original case and cables.",
  }),
  ad({
    id: "AD-10259",
    title: "Villa Renovation & General Contracting",
    category: "Services",
    location: "Muscat, Bosher",
    userName: "Falaj Build Co.",
    status: "Active",
    price: 0,
    postedDate: "2026-07-24",
    expiryDate: "2026-09-07",
    featured: true,
    views: 520,
    clicks: 71,
    description: "Full renovation, permits handled, free site visit and quote.",
  }),
  ad({
    id: "AD-10260",
    title: "Kia Sportage 2023 — Low Mileage",
    category: "Motors",
    location: "Muscat, Seeb",
    userName: "Amal Al Busaidi",
    status: "Active",
    price: 9800,
    postedDate: "2026-08-02",
    expiryDate: "2026-09-16",
    featured: false,
    views: 1680,
    clicks: 214,
    description: "Single owner, full service history, still under manufacturer warranty.",
  }),
  ad({
    id: "AD-10261",
    title: "Customer Service Representative — Part Time",
    category: "Jobs",
    location: "Muscat, Ruwi",
    userName: "Oman Retail Group",
    status: "Pending",
    price: 0,
    postedDate: "2026-08-11",
    expiryDate: "2026-09-25",
    featured: false,
    views: 35,
    clicks: 4,
    description: "Evening shifts, fluent in Arabic and English, retail experience preferred.",
  }),
  ad({
    id: "AD-10262",
    title: "OnePlus 12 256GB",
    category: "Mobile & Tablets",
    location: "Muscat, Al Amerat",
    userName: "Waleed Al Siyabi",
    status: "Active",
    price: 210,
    postedDate: "2026-08-05",
    expiryDate: "2026-09-19",
    featured: false,
    views: 260,
    clicks: 31,
    description: "Excellent condition, screen protector applied since day one.",
  }),
  ad({
    id: "AD-10263",
    title: "Freehold Land — Al Ansab, 600 sqm",
    category: "Real Estate",
    location: "Muscat, Al Ansab",
    userName: "Bader Al Ghafri",
    status: "Active",
    price: 145000,
    postedDate: "2026-07-15",
    expiryDate: "2026-08-29",
    featured: true,
    views: 1980,
    clicks: 256,
    description: "Corner plot, residential zoning, all utilities available at boundary.",
  }),
  ad({
    id: "AD-10264",
    title: "Legal Consultancy — Contract Review & Drafting",
    category: "Services",
    location: "Muscat, Qurm",
    userName: "Al Habsi & Partners",
    status: "Rejected",
    price: 0,
    postedDate: "2026-08-08",
    expiryDate: "2026-09-22",
    featured: false,
    views: 29,
    clicks: 3,
    rejectionReason: "Listing category mismatch — please post under Services > Consultancy Services.",
    description: "Commercial and real estate contracts, bilingual documentation.",
  }),
  ad({
    id: "AD-10265",
    title: "Honda Civic RS 2021",
    category: "Motors",
    location: "Sur",
    userName: "Marwan Al Kalbani",
    status: "Active",
    price: 8200,
    postedDate: "2026-07-30",
    expiryDate: "2026-09-13",
    featured: false,
    views: 1340,
    clicks: 172,
    description: "Turbo engine, sunroof, well maintained, no accidents.",
  }),
  ad({
    id: "AD-10266",
    title: "Dell XPS 15 — i9 / 32GB / 1TB",
    category: "Electronics & Leisure",
    location: "Muscat, Al Khuwair",
    userName: "Nasser Al Balushi",
    status: "Sold",
    price: 480,
    postedDate: "2026-06-18",
    expiryDate: "2026-08-02",
    featured: false,
    views: 2110,
    clicks: 298,
    description: "4K OLED display, RTX graphics, purchased 6 months ago.",
  }),
  ad({
    id: "AD-10267",
    title: "Registered Nurse — Full Time, Muscat",
    category: "Jobs",
    location: "Muscat, Bosher",
    userName: "Al Shifa Medical Center",
    status: "Active",
    price: 0,
    postedDate: "2026-07-21",
    expiryDate: "2026-09-04",
    featured: true,
    views: 470,
    clicks: 63,
    description: "OMSB license required, ICU experience preferred, competitive package.",
  }),
  ad({
    id: "AD-10268",
    title: "Google Pixel 9 Pro 256GB",
    category: "Mobile & Tablets",
    location: "Muscat, Ghubrah",
    userName: "Hind Al Rawahi",
    status: "Pending",
    price: 295,
    postedDate: "2026-08-11",
    expiryDate: "2026-09-25",
    featured: false,
    views: 51,
    clicks: 6,
    description: "New, unopened box, GCC version with full warranty.",
  }),
  ad({
    id: "AD-10269",
    title: "Movers & Packers — Full Household Relocation",
    category: "Services",
    location: "Muscat, Ghala",
    userName: "SwiftMove Oman",
    status: "Active",
    price: 45,
    postedDate: "2026-07-19",
    expiryDate: "2026-09-02",
    featured: false,
    views: 690,
    clicks: 88,
    description: "Packing, loading, transport and unloading, insured service.",
  }),
]
